/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminReferralsRouteImport } from './routes/admin/referrals'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminDocsRouteImport } from './routes/admin/docs'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as SiteLoginRouteImport } from './routes/_site/login'
import { Route as SiteAuthErrorRouteImport } from './routes/_site/auth-error'
import { Route as SiteShopIndexRouteImport } from './routes/_site/shop/index'
import { Route as SiteReviewsIndexRouteImport } from './routes/_site/reviews/index'
import { Route as SiteReferralsIndexRouteImport } from './routes/_site/referrals/index'
import { Route as SiteProjectsIndexRouteImport } from './routes/_site/projects/index'
import { Route as SiteJustAskIndexRouteImport } from './routes/_site/just-ask/index'
import { Route as SiteDocsIndexRouteImport } from './routes/_site/docs/index'
import { Route as SiteCvIndexRouteImport } from './routes/_site/cv/index'
import { Route as SiteContactIndexRouteImport } from './routes/_site/contact/index'
import { Route as SiteBlogIndexRouteImport } from './routes/_site/blog/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SiteShopSlugRouteImport } from './routes/_site/shop/$slug'
import { Route as SiteProjectsSlugRouteImport } from './routes/_site/projects/$slug'
import { Route as SiteBlogSlugRouteImport } from './routes/_site/blog/$slug'
import { Route as SiteDocsSectionSlugRouteImport } from './routes/_site/docs/$section.$slug'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocsRoute = AdminDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const SiteLoginRoute = SiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAuthErrorRoute = SiteAuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopIndexRoute = SiteShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReviewsIndexRoute = SiteReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReferralsIndexRoute = SiteReferralsIndexRouteImport.update({
  id: '/referrals/',
  path: '/referrals/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsIndexRoute = SiteProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteJustAskIndexRoute = SiteJustAskIndexRouteImport.update({
  id: '/just-ask/',
  path: '/just-ask/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDocsIndexRoute = SiteDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCvIndexRoute = SiteCvIndexRouteImport.update({
  id: '/cv/',
  path: '/cv/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactIndexRoute = SiteContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteShopSlugRoute = SiteShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsSlugRoute = SiteProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDocsSectionSlugRoute = SiteDocsSectionSlugRouteImport.update({
  id: '/docs/$section/$slug',
  path: '/docs/$section/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth-error': typeof SiteAuthErrorRoute
  '/login': typeof SiteLoginRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
  '/shop/$slug': typeof SiteShopSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/contact/': typeof SiteContactIndexRoute
  '/cv/': typeof SiteCvIndexRoute
  '/docs/': typeof SiteDocsIndexRoute
  '/just-ask/': typeof SiteJustAskIndexRoute
  '/projects/': typeof SiteProjectsIndexRoute
  '/referrals/': typeof SiteReferralsIndexRoute
  '/reviews/': typeof SiteReviewsIndexRoute
  '/shop/': typeof SiteShopIndexRoute
  '/docs/$section/$slug': typeof SiteDocsSectionSlugRoute
}
export interface FileRoutesByTo {
  '/auth-error': typeof SiteAuthErrorRoute
  '/login': typeof SiteLoginRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
  '/shop/$slug': typeof SiteShopSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/blog': typeof SiteBlogIndexRoute
  '/contact': typeof SiteContactIndexRoute
  '/cv': typeof SiteCvIndexRoute
  '/docs': typeof SiteDocsIndexRoute
  '/just-ask': typeof SiteJustAskIndexRoute
  '/projects': typeof SiteProjectsIndexRoute
  '/referrals': typeof SiteReferralsIndexRoute
  '/reviews': typeof SiteReviewsIndexRoute
  '/shop': typeof SiteShopIndexRoute
  '/docs/$section/$slug': typeof SiteDocsSectionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_site/auth-error': typeof SiteAuthErrorRoute
  '/_site/login': typeof SiteLoginRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/projects/$slug': typeof SiteProjectsSlugRoute
  '/_site/shop/$slug': typeof SiteShopSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/contact/': typeof SiteContactIndexRoute
  '/_site/cv/': typeof SiteCvIndexRoute
  '/_site/docs/': typeof SiteDocsIndexRoute
  '/_site/just-ask/': typeof SiteJustAskIndexRoute
  '/_site/projects/': typeof SiteProjectsIndexRoute
  '/_site/referrals/': typeof SiteReferralsIndexRoute
  '/_site/reviews/': typeof SiteReviewsIndexRoute
  '/_site/shop/': typeof SiteShopIndexRoute
  '/_site/docs/$section/$slug': typeof SiteDocsSectionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/auth-error'
    | '/login'
    | '/admin/blog'
    | '/admin/docs'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/referrals'
    | '/admin/reviews'
    | '/admin/users'
    | '/dashboard/reviews'
    | '/admin/'
    | '/dashboard/'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/shop/$slug'
    | '/api/auth/$'
    | '/blog/'
    | '/contact/'
    | '/cv/'
    | '/docs/'
    | '/just-ask/'
    | '/projects/'
    | '/referrals/'
    | '/reviews/'
    | '/shop/'
    | '/docs/$section/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth-error'
    | '/login'
    | '/admin/blog'
    | '/admin/docs'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/referrals'
    | '/admin/reviews'
    | '/admin/users'
    | '/dashboard/reviews'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/shop/$slug'
    | '/api/auth/$'
    | '/blog'
    | '/contact'
    | '/cv'
    | '/docs'
    | '/just-ask'
    | '/projects'
    | '/referrals'
    | '/reviews'
    | '/shop'
    | '/docs/$section/$slug'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/dashboard'
    | '/_site/auth-error'
    | '/_site/login'
    | '/admin/blog'
    | '/admin/docs'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/referrals'
    | '/admin/reviews'
    | '/admin/users'
    | '/dashboard/reviews'
    | '/_site/'
    | '/admin/'
    | '/dashboard/'
    | '/_site/blog/$slug'
    | '/_site/projects/$slug'
    | '/_site/shop/$slug'
    | '/api/auth/$'
    | '/_site/blog/'
    | '/_site/contact/'
    | '/_site/cv/'
    | '/_site/docs/'
    | '/_site/just-ask/'
    | '/_site/projects/'
    | '/_site/referrals/'
    | '/_site/reviews/'
    | '/_site/shop/'
    | '/_site/docs/$section/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/docs': {
      id: '/admin/docs'
      path: '/docs'
      fullPath: '/admin/docs'
      preLoaderRoute: typeof AdminDocsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/login': {
      id: '/_site/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLoginRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/auth-error': {
      id: '/_site/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof SiteAuthErrorRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop/': {
      id: '/_site/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof SiteShopIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/reviews/': {
      id: '/_site/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof SiteReviewsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/referrals/': {
      id: '/_site/referrals/'
      path: '/referrals'
      fullPath: '/referrals/'
      preLoaderRoute: typeof SiteReferralsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects/': {
      id: '/_site/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof SiteProjectsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/just-ask/': {
      id: '/_site/just-ask/'
      path: '/just-ask'
      fullPath: '/just-ask/'
      preLoaderRoute: typeof SiteJustAskIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/docs/': {
      id: '/_site/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof SiteDocsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cv/': {
      id: '/_site/cv/'
      path: '/cv'
      fullPath: '/cv/'
      preLoaderRoute: typeof SiteCvIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact/': {
      id: '/_site/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof SiteContactIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/shop/$slug': {
      id: '/_site/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof SiteShopSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects/$slug': {
      id: '/_site/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof SiteProjectsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/docs/$section/$slug': {
      id: '/_site/docs/$section/$slug'
      path: '/docs/$section/$slug'
      fullPath: '/docs/$section/$slug'
      preLoaderRoute: typeof SiteDocsSectionSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAuthErrorRoute: typeof SiteAuthErrorRoute
  SiteLoginRoute: typeof SiteLoginRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteProjectsSlugRoute: typeof SiteProjectsSlugRoute
  SiteShopSlugRoute: typeof SiteShopSlugRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteContactIndexRoute: typeof SiteContactIndexRoute
  SiteCvIndexRoute: typeof SiteCvIndexRoute
  SiteDocsIndexRoute: typeof SiteDocsIndexRoute
  SiteJustAskIndexRoute: typeof SiteJustAskIndexRoute
  SiteProjectsIndexRoute: typeof SiteProjectsIndexRoute
  SiteReferralsIndexRoute: typeof SiteReferralsIndexRoute
  SiteReviewsIndexRoute: typeof SiteReviewsIndexRoute
  SiteShopIndexRoute: typeof SiteShopIndexRoute
  SiteDocsSectionSlugRoute: typeof SiteDocsSectionSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAuthErrorRoute: SiteAuthErrorRoute,
  SiteLoginRoute: SiteLoginRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteProjectsSlugRoute: SiteProjectsSlugRoute,
  SiteShopSlugRoute: SiteShopSlugRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteContactIndexRoute: SiteContactIndexRoute,
  SiteCvIndexRoute: SiteCvIndexRoute,
  SiteDocsIndexRoute: SiteDocsIndexRoute,
  SiteJustAskIndexRoute: SiteJustAskIndexRoute,
  SiteProjectsIndexRoute: SiteProjectsIndexRoute,
  SiteReferralsIndexRoute: SiteReferralsIndexRoute,
  SiteReviewsIndexRoute: SiteReviewsIndexRoute,
  SiteShopIndexRoute: SiteShopIndexRoute,
  SiteDocsSectionSlugRoute: SiteDocsSectionSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminDocsRoute: typeof AdminDocsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminDocsRoute: AdminDocsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
